In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\maaza\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\maaza\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\maaza\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\maaza\anaconda3\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\maaza\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Data/apple_products.csv')

In [4]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [5]:
df.count()

Product Name           62
Product URL            62
Brand                  62
Sale Price             62
Mrp                    62
Discount Percentage    62
Number Of Ratings      62
Number Of Reviews      62
Upc                    62
Star Rating            62
Ram                    62
dtype: int64

In [6]:
df['Mrp'].max()

149900

In [7]:
df['Mrp'].min()

39900

In [8]:
df[df['Mrp'] == 149900]

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
24,"APPLE iPhone 12 Pro (Silver, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-s...,Apple,140900,149900,6,542,42,MOBFWBYZ5UY6ZBVA,4.5,4 GB
41,"APPLE iPhone 12 Pro (Pacific Blue, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-p...,Apple,140900,149900,6,545,42,MOBFWBYZTHSXKMGW,4.5,4 GB

In [9]:
df[df['Mrp'] == 39900]

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,24,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB

In [10]:
df[df['Mrp'] <= 50000]

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
5,"APPLE iPhone 8 Plus (Silver, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,0,3431,356,MOBEXRGVQGYYP8FV,4.6,2 GB
6,"APPLE iPhone 8 Plus (Space Grey, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,0,3431,356,MOBEXRGVQKBREZP8,4.6,2 GB
10,"Apple iPhone XR (Black, 64 GB) (Includes EarPo...",https://www.flipkart.com/apple-iphone-xr-black...,Apple,39999,47900,16,79512,6796,MOBF9Z7ZPHGV4GNH,4.6,4 GB
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,24,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB
53,"APPLE iPhone SE (Black, 128 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,34999,44900,22,95909,8161,MOBFWQ6BHUEVZPXD,4.5,2 GB
54,"APPLE iPhone SE (White, 128 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,34999,44900,22,95807,8154,MOBFWQ6BJEHMUUZY,4.5,2 GB
55,"APPLE iPhone SE (Red, 128 GB)",https://www.flipkart.com/apple-iphone-se-red-1...,Apple,34999,44900,22,95909,8161,MOBFWQ6BJTVFKPEJ,4.5,2 GB
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB

In [11]:
df['Product Name']

0            APPLE iPhone 8 Plus (Gold, 64 GB)
1     APPLE iPhone 8 Plus (Space Grey, 256 GB)
2         APPLE iPhone 8 Plus (Silver, 256 GB)
3              APPLE iPhone 8 (Silver, 256 GB)
4                APPLE iPhone 8 (Gold, 256 GB)
                        ...
57              APPLE iPhone SE (Black, 64 GB)
58             APPLE iPhone 11 (Purple, 64 GB)
59              APPLE iPhone 11 (White, 64 GB)
60              APPLE iPhone 11 (Black, 64 GB)
61                APPLE iPhone 11 (Red, 64 GB)
Name: Product Name, Length: 62, dtype: object

In [12]:
type(df['Product Name'])

pandas.core.series.Series

In [13]:
list(df['Product Name'])[0:5]

['APPLE iPhone 8 Plus (Gold, 64 GB)',
 'APPLE iPhone 8 Plus (Space Grey, 256 GB)',
 'APPLE iPhone 8 Plus (Silver, 256 GB)',
 'APPLE iPhone 8 (Silver, 256 GB)',
 'APPLE iPhone 8 (Gold, 256 GB)']

In [14]:
list(df['Product Name'])[0][6:15]

'iPhone 8 '

In [15]:
list(df['Product Name'])[0][6:15].strip()

'iPhone 8'

In [16]:
df['Model Name'] = df['Product Name'].str[6:15]

In [17]:
df['Model Name'].head()

0    iPhone 8
1    iPhone 8
2    iPhone 8
3    iPhone 8
4    iPhone 8
Name: Model Name, dtype: object

In [18]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Model Name
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,iPhone 8
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,iPhone 8
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,iPhone 8
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB,iPhone 8
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB,iPhone 8

In [19]:
# Better using regex
pattern = r'APPLE\s(.*?)\s\('
df['Full Model Name'] = df['Product Name'].str.extract(pattern)

In [20]:
df['Full Model Name'].head()

0    iPhone 8 Plus
1    iPhone 8 Plus
2    iPhone 8 Plus
3         iPhone 8
4         iPhone 8
Name: Full Model Name, dtype: object

In [21]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Model Name,Full Model Name
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,iPhone 8,iPhone 8 Plus
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,iPhone 8,iPhone 8 Plus
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,iPhone 8,iPhone 8 Plus
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB,iPhone 8,iPhone 8
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB,iPhone 8,iPhone 8